### PR TITLE
docker/vpp-cni: make a few small fixes

### PR DESCRIPTION
**Pull request by unclejack**
This PR makes a few changes and fixes which should've been part of https://github.com/contiv/vpp/pull/559.

### CODE REVIEW

**Comment by tiewei** [comment]
I think you missed the change that changes "chmod +x install.sh"

**Comment by unclejack** [comment]
@tiewei: No, I've made that change and a few other changes to install.sh.

**Comment by tiewei** [comment]
@unclejack  sorry i overlooked it

**Comment by unclejack** [comment]
@tiewei: I've updated the PR to change the commit message.

**Pull request merged**
